# This file was initially generated by terraspace_plugin_aws 0.5.0
# Backend Config Variables Docs
# https://terraspace.cloud/docs/config/backend/variables/
terraform {
  backend "s3" {
    bucket         = "magic-wand-tfstate"
    key            = "<%= expansion(':REGION/:ENV/:BUILD_DIR/terraform.tfstate') %>"
    region         = "<%= expansion(':REGION') %>"
    encrypt        = true
    dynamodb_table = "terraform_locks"
  }
}
